# REST API

## Get All Profiles
### curl http://localhost:3000/profile
GET http://localhost:3000/profile
### Crate new Profile
### curl -X POST  http://localhost:3000/profile
POST http://localhost:3000/profile
Content-Type: application/json

{
    "username": "BeamX2",
    "password": "1234",
    "mobile": "0123456788",
    "cardId": "1234567890122"

}